### PR TITLE
update radio firmware to 6.8.11

### PR DESCRIPTION
**Pull request by tmaone**
Change-Id: I4e7383e7ae990f247171416103171442765d5c49

### CODE REVIEW

**Comment by tmaone** [comment]
I will be updating the blobs too. If you're not interested or not accepting external PRs let me know and feel free to decline.

**Comment by h2o64** [comment]
Two things:
1- We are working on changing our firmware shipping current state as many people warned us against it
2- As we seen with previous 6.8.XX releases, they are extremly ephemer, consequently, we'd rather wait a bit to see their durability and stability as stock roms first.

**Comment by tmaone** [comment]
True, I've seen too quite a number of changes in each of the latest releases.
Out of curiosity, what do you mean in (1)? I'm not sure I got it.
Also, are you interested in PRs and any help or prefer to work on your own commits?

**Comment by bgcngm** [comment]
In addition to above, I see that 6.8.11 is the dev Global package. This is the first time I see an official MIUI 8 release on global channel, if I am right. So far, we were only using blobs and firmware from dev China packages.

**Comment by tmaone** [comment]
From a brief look I see that firmware blobs from 8.11 Global Dev, are identical with the ones from 8.12 CN dev. Looking more closely right now, but it seems they are really the same.

**Comment by bgcngm** [comment]
Honestly, we'd prefer to see contributions on device tree. Caution is needed when it comes to changes in the vendor side because there are now some "special" blobs that can't be updated at all. I hope you don't mind, but having to pay attention to this PR's requires us more time than actually updating blobs ourselves.

**Comment by tmaone** [comment]
Sure! Thanks anyway. 
I will be working on this for me for some time, in case anything interesting comes up in my forks let me know. Any particular area you'd prefer in the device tree? Since I haven't followed the vendor progress from the beginning, are you referring to things such as the gfx/gles adreno libs, or recent changes in the radio fw bins?

**Comment by bgcngm** [comment]
Not only graphics blobs have diverged lately, also DPM service app and QTI telephony extension blobs should not be touched.

As far as it concerns to the device tree, any good contribution is well accepted. For your info, there are currently two big issues to address:
 - performance issues when battery goes bellow 5% 
 - sensors (accel, compass and gyro) dying after some heavy GPS usage

**Comment by tmaone** [comment]
Good to know, I will have this in mind. Thanks again!

**Comment by bgcngm** [comment]
Thanks to you for your willing to help. It's good to see more people interested in contributing to this project and not to simply making use of it to take credits.

**Comment by bgcngm** [comment]
Merged in ebfeb3e818cd7f6b6b0e0783fa8e3ae4a38336ef.

**Comment by tmaone** [comment]
Tx! Saw it now. I'm afraid latest fw (6.8.18) might have undesirable (braking -- perhaps related to drm/wildv.) changes.

**Comment by bgcngm** [comment]
Why do you say that. Global ROM is supposed to include DRM support.

**Comment by tmaone** [comment]
Sure it always did. I was trying the new blobs and saw way too many logcat errors, wrt to missing /dev paths (perhaps updates in devcfg) and libraries not found. Haven't had the time to go through thoroughly, just a radare diff on between the previous and current versions.

**Comment by bgcngm** [comment]
IIRC, the only blobs that are not found on 6.8.18 are IMS related (vendor/lib64/libimscamera_jni.so
and vendor/lib64/libimsmedia_jni.so). To be honest, I'm very reluctant to updating the blobs since the last update, since they fixed the long-time dying sensors issue.

**Comment by tmaone** [comment]
Second that. Network and reception-wise, this last update has been fantastic so far. Not sure why I'm feeling reluctant on subsequent updates as well. Might be just me paying attention to unimportant things, or indeed several things start to finalise / get restricted as they are heading towards final release. Will check it though and update on findings.

**Pull request closed without merging**
